import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import Link from "next/link"
import ParallaxHero from "@/components/parallax-hero"
import Background from "@/assets/background_6.jpg"

export default function NewsImpactCalculatorTermsPage() {
  return (
    <main className="min-h-screen">
      <Navbar />

      <ParallaxHero
        image={Background}
        title="News Impact Calculator"
        subtitle="Terms of Service"
      />

      <section className="py-20 px-6">
        <div className="container mx-auto">
          <div className="max-w-3xl mx-auto">
            <Link
              href="/tools/newsimpactcalculator"
              className="inline-flex items-center gap-1 text-sm font-semibold text-blue-900 transition hover:text-blue-700"
            >
              ← Back
            </Link>

            <h1 className="mt-6 text-3xl md:text-4xl font-bold text-gray-900">News Impact Calculator - Terms of Service</h1>
            <p className="mt-2 text-gray-600">
              <strong>Last updated:</strong> May 2026
            </p>

            <p className="mt-6 text-gray-700">
              News Impact Calculator is a free research prompt module. By using this tool, you agree to the following terms.
            </p>

            <section className="mt-8 space-y-6 text-gray-700">
              <div>
                <h2 className="text-2xl font-semibold text-gray-900">1. Educational Use</h2>
                <p>
                  News Impact Calculator is provided for educational and research purposes only. It does not provide financial
                  advice, trading signals, or investment recommendations.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">2. No Warranty</h2>
                <p>
                  This tool is provided "as is" without warranties of any kind. We make no guarantees regarding reliability,
                  availability, or accuracy.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">3. Limitation of Liability</h2>
                <p>
                  We are not liable for any damages arising from the use or inability to use the tool, including decisions made
                  based on its outputs or guidance.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">4. User Responsibility</h2>
                <p>
                  You are responsible for how you use the prompt and any outputs generated by third-party tools or services.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">5. Third-Party Services</h2>
                <p>
                  The tool references external services that are not operated by us. Use of those services is subject to their
                  own terms and policies.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">6. Modifications</h2>
                <p>We may update or modify the tool at any time.</p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-gray-900">7. Acceptance</h2>
                <p>By using News Impact Calculator, you agree to these terms.</p>
              </div>
            </section>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
